### PR TITLE
Upload Images Function to Frontend and S3 (Resolves #132, #112, #157) 

### LINKED ISSUE #132: "Make a Donation - Item Information" Uploading images
### Description
This task will deal for uploading images for the donations. People might log in from a variety of different platforms such as: Windows, MacOS, iOS, Android OS and that must be accounted for. This task will require a little research to find out how to upload photo files.

### Success Metrics Checklist
- [x] Research how to upload images
- [x] Update page to look like the Figma
- [x] Photos will upload
- [x] Display photos or a confirmation message once uploaded

image

Finally, on your pull request, please request a code review from Josh (@ObjectJosh) or me (@scallait )

### PR DESCRIPTION
**Pull request by hnadrian**
### Pull Request Summary

This pull request allows the users to upload images to the website, which can then be sent to S3 and the database.
For issues #132, #112 and #157

### Changes:

- Images can be uploaded to the front-end with previews (with file size and count limits).
- Added Image compression
- Images are uploaded to S3 and their Presigned Urls are retrieved for preview.
- Added clear images for reupload, which also deletes the images from S3 bucket.

Note: The image is stored when the user uploads to the front end and not when submission because we need a URL from S3 to be stored in the state.

Screen Shot 2023-03-08 at 4 30 52 PM
Screen Shot 2023-03-08 at 4 31 04 PM
Screen Shot 2023-03-08 at 4 31 29 PM

### CODE REVIEW

**Comment by ObjectJosh** [comment]
Presigned Urls -> expire over time so you might need to check if it's expired

**Comment by ObjectJosh** [comment]
- S3 Bucket public -> then urls are available forever

**Comment by ObjectJosh** [comment]
- Note: Mobile uploading

**Comment by ObjectJosh** [comment]
Screen Shot 2023-03-15 at 5 32 59 PM
Receiving an error when trying to upload an image in `imageRoutes.js`

**Review by ObjectJosh — CHANGES_REQUESTED** [review]

**Review by ObjectJosh — CHANGES_REQUESTED** [review]
@hnadrian Please let me know if you're getting the error above when uploading an image

**Comment by hnadrian** [comment]
> @hnadrian Please let me know if you're getting the error above when uploading an image

I do not encounter this error, however, I updated the way location is initialized that perhaps will fix this issue

**Comment by hnadrian** [comment]
Pull request should be ready to be merged

**Review by ObjectJosh — APPROVED** [review]
Great work adrian

**Pull request merged**
