### PR TITLE
14-Donator-Next-Steps (resolves #14)

### LINKED ISSUE #14: Create "Make a Donation - Next Steps" Page for Donator View
### Description
Create the "Make a Donation - Next Steps" screen based on [Figma](https://www.figma.com/file/MNRQAXLXzBqCR3aRZmXg0T/Habitat-for-Humanity). Don't worry about the navbar at the top for this task (this will be assigned in a separate issue). For this screen, please reuse this component: 
Screen Shot 2022-01-08 at 6 06 10 PM

 and adjust it according to your screen on Figma, instead of coding it from scratch. Check the Figma to see which screen you may be able to get it from! _(Hint: it's also in the donator view)_ The component _should_ be completed by the time you start this task... but if not, just leave said component blank and let me know in a comment when submitting the pull request.

### Setup
1. Navigate to `/frontend/src/components/`
2. Create a folder named "donation" _(if it already exists, skip this step)_
3. Navigate into that folder named "donation"
4. Create a folder with the [PascalCase](https://techterms.com/definition/pascalcase) naming convention (name based on the component you're working on)
5. Inside the folder, create a `.tsx` file with the same name as the folder
6. Be sure to update the `App.js` file with your new component, or else you wont see any changes you make. This file is located in `/frontend/src/`

### Success Metrics Checklist
- [x] Looks exactly like the Figma (again, disregarding the navbar)
- [x] Responsive screen handling
- [x] Prompt user to make a call when phone number is clicked (Refer to the functionality of [their website](https://hfhsloco.org/)'s contact section at the bottom)

Finally, on your pull request, please request a code review from me (@ObjectJosh)

Screen Shot 2022-01-08 at 6 07 13 PM

### PR DESCRIPTION
**Pull request by tessa-tapmongkol**
image

### CODE REVIEW

**Review by ObjectJosh — APPROVED** [review]
Perfect!

**Comment by scallait** [comment]
Hi @tessa-tapmongkol @ObjectJosh. I noticed while doing navigation for the pages that the next steps page has a "back" and "next" button.
image

On the figma though I see there is only a **done** button:
image

Would you like me to still do the **back** and **next** buttons or just change it to a **done** button

**Comment by tessa-tapmongkol** [comment]
@scallait thanks for letting me know! The design must've changed. I can make a PR right now to change that to a done button -- I would just follow the design on Figma

**Comment by scallait** [comment]
@tessa-tapmongkol I can take care of it if you'd like. It'll only take a minute since I already have it up.

**Comment by tessa-tapmongkol** [comment]
@scallait Oops just saw this, but I just submitted the changes in this [PR ](https://github.com/hack4impact-calpoly/habitat-for-humanity/pull/66)

**Comment by ObjectJosh** [comment]
@scallait Changes are merged in -- thanks for checking! @tessa-tapmongkol thanks for fixing it so quickly!

**Pull request merged**
