### PR TITLE
Added a mobile view for Make a Donation(resolves #125)

### LINKED ISSUE #125: Mobile View for "Make a Donation - Item Info" Page
### Description
Responsively switch to mobile view for "Make a Donation - Item Info" page based on [Figma](https://www.figma.com/file/MNRQAXLXzBqCR3aRZmXg0T/Habitat-for-Humanity).
(Screens less than 640px width)

### Success Metrics Checklist
- [ ] Looks exactly like the Figma

Finally, on your pull request, please request a code review from me (@ObjectJosh)

Screen Shot 2022-01-19 at 11 13 46 PM

### PR DESCRIPTION
**Pull request by eduardo661**
I created the mobile view for the make a donation page. added media queries to the inline css styling.

Screen Shot 2023-02-01 at 5 22 50 PM

### CODE REVIEW

**Comment by ObjectJosh** [comment]
Eduardo, are you getting any errors from prettier when running it?

**Comment by eduardo661** [comment]
No, not from what I see. Is the code giving you any prettier errors?

**Comment by ObjectJosh** [comment]
@eduardo661 Yup, a couple hundred

**Comment by ObjectJosh** [comment]
@eduardo661 Did you make this new branch off main or dev?

**Comment by eduardo661** [comment]
I think I branched off of main. is there anything I should redo in that case?

**Comment by ObjectJosh** [comment]
@eduardo661 You'll need to select to merge into `dev` instead of main when making your pull request

**Pull request closed without merging**
